services:
  redis:
    image: redis:7.2
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  minio:
    image: minio/minio:latest
    container_name: minio_server
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  law-app:
    build: .
    container_name: law_app
    depends_on:
      - redis
      - minio
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_REDIS_HOST: redis
      MINIO_URL: http://minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    volumes:
      - ./logs:/app/logs

volumes:
  redis_data:
  minio_data:
